### PR TITLE
Add standard github header

### PR DESCRIPTION
**Pull request by maximedenes**

### CODE REVIEW

**Comment by Zimmi48** [comment]
Very good idea!

**Comment by Zimmi48** [comment]
Shall we merge this?

**Comment by maximedenes** [comment]
I'm preparing a series of small PRs for the website, I can merge them once it is done, no strong opinion.

The only thing I don't quite like about this one is that good color matching is very hard to achieve with the current bordeaux of the website, so I took the standard github color that was the least ugly match, but it's not better than okay.

**Comment by Zimmi48** [comment]
I think it looks OK like this. It's more adapted to "modern" clearer designs but it's not ugly like this.

**Pull request merged**
