### PR TITLE
news: 8.13+beta1

### PR DESCRIPTION
**Pull request by gares**

### CODE REVIEW

**Comment by gares** [comment]
is there a CI here?

**Comment by gares** [comment]
locally it looks "ok" but I don't have a CSS, so... it mainly shows firefox can parse the tags

**Comment by Zimmi48** [comment]
> locally it looks "ok" but I don't have a CSS, so... it mainly shows firefox can parse the tags

You can do `make run` after `make` to have a relatively good preview of the final results.

**Review by Zimmi48 — APPROVED** [review]
LGTM (tested locally)

**Pull request merged**
