### PR TITLE
Update Consortium page

### PR DESCRIPTION
**Pull request by maximedenes**
We try to reflect better the current situation, in particular the various options for partners.

### CODE REVIEW

**Comment by Zimmi48** [comment]
Note #149: you'll have to run the sync script manually after merging.

**Comment by maximedenes** [comment]
@ybertot I added some information about what the membership means. Does the phrasing look ok to you?

**Comment by gares** [comment]
Since when Gold is more than platinum? Did you mean silver?

**Comment by maximedenes** [comment]
> Since when Gold is more than platinum? Did you mean silver?

Thanks, I inverted the two in the list. The description is ok.

**Comment by maximedenes** [comment]
Fixed.

**Comment by Zimmi48** [comment]
Should the home page of the website still contain the word "sponsor"?

**Pull request merged**
