### PR TITLE
Update index.html remove will be released in june

### PR DESCRIPTION
**Pull request by thery**

### CODE REVIEW

**Comment by Zimmi48** [comment]
This solution is not entirely satisfying to me (the UPCOMINGDATE variable does not serve any purpose anymore) but something needs to be done anyway. Letting @vbgl decide.

**Comment by vbgl** [comment]
You might want to put “July” instead of “June”. Or “summer”.

**Comment by thery** [comment]
@Zimmi48 @vbgl What about *soon* ;-)

**Comment by maximedenes** [comment]
What's the current target date?

**Comment by Zimmi48** [comment]
Obsolete

**Pull request closed without merging**
