### PR TITLE
Add info about gitter.

### PR DESCRIPTION
**Pull request by jfehrle**

### CODE REVIEW

**Comment by Zimmi48** [comment]
Thanks! It would probably be worth adding a link in the bottom section as well (see `<div class="frameworklinks">` below).

**Comment by jfehrle** [comment]
I added the link.

I also notice that the color for links is hard to distinguish from the color for the text.  The highlight is 96,5,8.  I have to pay close attention to pick out the links, that seems too subtle.  I guess the color was chosen to look similar to the header bar.  The text is not even black, it's 68,68,68 (the headers, such as "What is Coq?" are black, though: 0,0,0).  Shall we change the highlight color, too?

**Comment by Zimmi48** [comment]
I never had any problems distinguishing these two colors but if you have, then we should fix this. If you have a concrete suggestion, I'll let you open a new PR about that.

BTW, quick English question: you removed "The" in front of "Coq developers" in the third paragraph but not after "You can contact" in the first paragraph. Any particular reason to justify that the latter is OK?

**Comment by jfehrle** [comment]
Perhaps the colors come out differently for you.  Here's what I see in Chrome:

image

I think the highlight is less apparent when you look at the page, which is almost entirely text, like a book.
15 minutes investigation doesn't reveal where this color is set.  If you know where it is set, I'll make the change, but otherwise I'll let it go for now.  I don't see this color defined in C:/coqwww/www/styles/coq/style.css in hex or otherwise.

"The Coq developers and ..." would refer to all Coq developers; clearly that's not entirely accurate because some Coq developers do not attend Working Groups.  Also I expect each Coq developer does not attend every Working Group.  I assume "Coq developers" is meant to include anyone who commits code to Coq.

For "You can contact the Coq developers" it seems much more likely that all Coq developers are indeed reachable through coqdev or gitter--or should be.  Without "the", I might wonder which Coq developers it refers to.  Also this sentence echos the title just above it "The Coq development team".

The following seems a good description even though "Coq developers" is plural while all the examples are grammatically singular.

> We also use the definite article:
>
> • to say something about all the things referred to by a noun:
>
>The wolf is not really a dangerous animal (= Wolves are not really dangerous animals)
The kangaroo is found only in Australia (= Kangaroos are found only in Australia)
The heart pumps blood around the body. (= Hearts pump blood around bodies)

https://learnenglish.britishcouncil.org/en/english-grammar/determiners-and-quantifiers/definite-article

**Comment by Zimmi48** [comment]
Thanks!
About the defined style, I don't know anything about it. @letouzey might know more and be of help.

**Pull request merged**
