### PR TITLE
update ocaml version for opam

### PR DESCRIPTION
**Pull request by thery**
https://coq.zulipchat.com/#narrow/stream/237977-Coq-users/topic/Ocaml.20recommended.20version

### CODE REVIEW

**Comment by Zimmi48** [comment]
I agree that using the oldest compatible OCaml version in this doc is probably not a good idea. However, the conclusion from this discussion doesn't seem completely settled on recommending 4.10.2 yet. It seems that 4.13.1+flambda is another good option.

**Comment by thery** [comment]
I think we should stick with the choice of Coq Platform.

**Comment by Zimmi48** [comment]
That makes sense to me because the choice of the Platform will be a widely tested option. On the other hand, something to keep in mind is that the Platform has to make a compromise and usually cannot use the latest OCaml version because some of the packages it includes won't be compatible with it. This is why it doesn't use 4.13 yet (although that should become possible soon IIRC).

Anyway, if we want to settle on the policy that the documented recommended OCaml version should match the one of the Platform, then it would be good to add a comment documenting this policy next to the OCaml version definition.

**Comment by thery** [comment]
@Zimmi48  ok added the comment

**Pull request merged**
