### PR TITLE
Add a redirection to have a nix-shell for mathcomp

### PR DESCRIPTION
**Pull request by CohenCyril**
CC @Zimmi48

### CODE REVIEW

**Comment by CohenCyril** [comment]
Sorry I did a mistake and put your name in a commit log... I will rewrite it ASAP...

**Comment by Zimmi48** [comment]
The only way to check that this works is to merge the PR. Just a question though (I don't know anything about Apache), why did you put `R` instead of `R=301` like on the other lines? What is the difference? Or are these the same?

**Comment by CohenCyril** [comment]
[R] is [R=302] (HTTP code for moved temporarily) by default, while [R=301] is a moved permanently.

**Comment by Zimmi48** [comment]
I see, thanks!

**Pull request merged**
