### PR TITLE
Redirection for coq-nix-toolbox

### PR DESCRIPTION
**Pull request by CohenCyril**
CC @Zimmi48

### CODE REVIEW

**Comment by gares** [comment]
Do you really want to point to master here?

FTR I personally find the GH actions convention nice, eg coq.inria.fr/nix/toolbox/v1 to mean the latest v1.xxx

**Comment by CohenCyril** [comment]
It's not 100% clear to me yet ...

**Comment by CohenCyril** [comment]
It's a tool which self pins itself to the latest version on initialization, and then you never use the url but the pin.
In a sense this URL is to be used for initialization, it's like "dowload the latest version and pin it". What would make sense is an option to select a version while lauching the tool.

TL;DR: I think it makes sense it points to master this one. And since the redirect is temporary we can change our minds later on.

**Comment by CohenCyril** [comment]
Closed by mistake, I cannot seem to reopen it, github is lagging

**Comment by gares** [comment]
It's open, I let you merge

**Comment by Zimmi48** [comment]
Indeed, as long as we don't push random broken commits to `master`, it's fine to use that branch since it's then pinned to one particular commit. Later on, we can even decide to only push commits that get a tag to `master`. That's the git-flow convention. We have settled on this convention with Erik for the Docker-Coq-Action but with `v1` as the "master branch" and `master` as the "dev branch".

**Comment by Zimmi48** [comment]
Also, as Cyril said, we can easily change our mind and point to another location later on.
I don't think he has merge rights on this repo, so I'll merge now.

**Pull request merged**
