### PR TITLE
Add web page for the Coq Workshop 2016

### PR DESCRIPTION
**Pull request by jnarboux**
As organizer for Coq Workshop 2016 I would like to add the webpage on Coq's site as for previous years.

### CODE REVIEW

**Comment by jnarboux** [comment]
Thank you Enrico for merging, the web page seems to be updated: https://coq.inria.fr/coq-workshop
but the link does not work, I was working locally after running make.

Should I fix something ? or do we wait for some scripts ?

**Comment by gares** [comment]
To me your changes are OK so I need to debug the thing on the web server.  @maximedenes has ssh access to the machine, but not today since sysadmins are shutting down nas servers with ssh keys.
:-/

**Comment by herbelin** [comment]
At least Pierre would know. A suspicion is that because the link has a slash in it, the apache server may have to be restarted, but indeed, we'll have to wait for the ssh access to come back. I let you, or Maxime, or Pierre, do what is necessary.

**Comment by jnarboux** [comment]
It works now, thanks.

**Pull request merged**
