### PR TITLE
Announce Coq 8.12+beta1.

### PR DESCRIPTION
**Pull request by Zimmi48**
@ejgallego This announcement includes a call for help to improve the documentation on which we've been working with @jfehrle.

### CODE REVIEW

**Comment by ejgallego** [comment]
Very nice, thanks! I've never merged in this repos so I'm unsure if some action is needed on my part.

**Comment by Zimmi48** [comment]
I'll merge myself when the time is right: we first need to create the GitHub release. I was still hoping that the 8.11.2 release would be announced first, but we cannot delay forever.

**Comment by ejgallego** [comment]
> I'll merge myself when the time is right: we first need to create the GitHub release. I was still hoping that the 8.11.2 release would be announced first, but we cannot delay forever.

IMHO let's go ahead with the GH release at least.

**Comment by Zimmi48** [comment]
OK, feel free to create it today, or I can do it tomorrow.

**Pull request merged**
