### PR TITLE
Remove normal weights for links

### LINKED ISSUE #174: [Team page] People's names are in two different fonts.
>People's names are in two different fonts, how about fixing that?  Eg:
>
>image
>
>The boldface on this one seems inconsistent with the other entries:
>
>image
>
>Also, more trivially, "Coq-community manager" is capitalized differently for @Zimmi48 and @palmskog

_Originally posted by @jfehrle in https://github.com/coq/www/issues/172#issuecomment-872705392_

Note that the different fonts correspond to people whose name links to a website or not.

### PR DESCRIPTION
**Pull request by Alizter**
This should be inherited from the base style.

Fixes #174

### CODE REVIEW

**Comment by Alizter** [comment]
cc @Zimmi48

**Comment by Zimmi48** [comment]
Does not seem sufficient to fix the issue:
Screenshot 2021-09-27 at 13-24-01 Coq Team The Coq Proof Assistant

**Comment by Alizter** [comment]
Whoops that was the wrong style sheet. This should now fix it. By the way, which font do we actually want? The thinner one looks better to me imo, but I've defaulted to the thick one here.

**Comment by Zimmi48** [comment]
I also prefer the thinner version.

**Comment by Alizter** [comment]
Alright, I've changed it to a thin one now.

**Comment by Zimmi48** [comment]
Thanks a lot for fixing this @Alizter!

**Pull request merged**
