### PR TITLE
add Github link to Community page

### PR DESCRIPTION
**Pull request by psteckler**
Such a link was requested in https://coq.inria.fr/bugs/show_bug.cgi?id=4570.

### CODE REVIEW

**Comment by Zimmi48** [comment]
There are already tarballs for downloading Coq source, so I would rather say "you can follow the development on the Coq GitHub repository"
(remark in passing, I think the official way of writing it is GitHub, not Github)

**Comment by psteckler** [comment]
Change made, commits squashed.

**Comment by Zimmi48** [comment]
@maximedenes Can you merge this? (Not sure you receive notifications for this repo, thus the explicit @-mention).

**Comment by Zimmi48** [comment]
Thanks!

**Pull request merged**
