### PR TITLE
Updating contents of section user interfaces

### PR DESCRIPTION
**Pull request by herbelin**
This is a proposal to update the contents of the section on user interfaces (adding jscoq, vscoq, company-coq; clarifying peacoq, proofweb, ...).

I tried to reflect the diversity I know of existing interfaces but I'm not a specialist and I may have been ignorant or partial in my panorama. Combining our different perceptions of the situation would be useful.

### CODE REVIEW

**Comment by gares** [comment]
You should probably remove the Coq/Jedit experiment since nobody maintains it.  90% of it was merged in Coqoon, so there is really nothing to find in Coq/Jedit

**Comment by herbelin** [comment]
@gares: can you tell more about the 90% merged in Coqoon? Does it mean that only 10% of the code of Coq/jEdit is specific to jEdit? If yes, this looks like a very interesting indicator on the "universality" of the work on asynchronous evaluation.

Can you tell more about the experiment itself? For instance, assuming someome fluent in jEdit wants to use Coq with jEdit, does it make sense to propose him/her to be maintainer, or there are deepeer reason than the absence of a current maintainer for throwing away the work already done?

At least, I just tried to install it and get an opinion from myself. It fails for a reason which does not seem to be unsolvable: "host:port or stdfds expected after option -main-channel".

**Comment by gares** [comment]
JEdit and Coqoon are both written in java, so the PIDE part is the same (including the code chopping the text into sentences that is Coq specific).  The ML part, pidetop, is the same.  What is left in the Coq/jEdit experiment is the file with syntax highlight rules, that is jEdit specific and was made taking the one of CoqIDE and adapting it, IIRC.

By removing the link on the homepage you throw away nothing, you are just kind with the readers, that won't end up downloading a non working and non maintained UI.  You don't put Pcoq there, don't you?  Why?
Note that my remark also applies to proofweb. 

Tools that don't work should be listed in a dedicated section,
about the history of the system, not about the present.  They all had an important role in the past, they deserve to be listed, but they should not be confused with tools that work today. You don't find a download link for "Netscape 5" in the webpage of Firefox, even if it all begun from there.

**Comment by herbelin** [comment]
@gares: I understand your wish of removing the link to jEdit, but I don't understand why even the 10% with syntax highlight rules would not be worth to be advocated, would not be worth to be maintained by someone if we can find one. Was the experience negative? Are you recommending never using jEdit in the absolute? This work was done in a project which ended only a few months ago. Are you saying that you disapproved this project? Are you saying that the work you contributed to was an error? Are you saying that the results of this project are not worth any more to be maintained by anyone? Are you saying that spending a number of minutes to make it working is not worth (a number of minutes which maybe is even less than the time we are using to have this discussion!)?

As for proofweb, even if the version behind is 8.1 (actually trunk from 2008), it seems perfectly usable for the purpose of a demo, for the purpose of showing Coq to a friend without installing it, etc..., so it seems to still make some sense. Moreover, we know people in Nijmegen and it is certainly not a big deal to ask them to update the version of Coq running.

For the record, Pcoq was actually listed even until last year. It was then definitely clear that the effort to install an interface which requires "La bonne version de ocaml - 3.06 -, la bonne version du kit de développement Java - 1.4 -, une installation locale de la bonne version - 7.4 - du système Coq" was absurd to be advertised at this level any more.

To make a clearer separation between those interfaces which "work" and those which do not "work", which criterion would you use?

**Comment by gares** [comment]
Given that Karst left academia, I'm the only other "author" of the experiment.  I don't maintain it.  Please remove it from the page, or move it to another section saying it is discontinued in favor of Coqoon.

**Comment by herbelin** [comment]
@gares: I understand perfectly that you don't want to maintain it. What I don't understand is why you oppose to the idea that someone else could maintain it. You made this work in the context of a project and this is a result of the project. Why to be so negative on the possible continuations to give to this project? Again, it is perfectly fine if you don't want to be involved anymore in it. But no need to be negative regarding what is in the perimeter of what you don't want to be involved in.

**Comment by Zimmi48** [comment]
These changes are useful. I find it stupid that they are blocked on a debate whether to remove or not the JEdit plugin. I tend to agree with @gares: removing a reference to a work from this page doesn't mean making any judgment on this work, except that it isn't currently one that we choose to advertise.

**Comment by herbelin** [comment]
@Zimmi48: Your proposal seems indeed the only possible conclusion.

**Pull request closed without merging**
