### PR TITLE
Mention Iris in "What is Coq".

### PR DESCRIPTION
**Pull request by robbertkrebbers**

### CODE REVIEW

**Comment by robbertkrebbers** [comment]
> I'd go even further and remove Bedrock (Bedrock is dead and Bedrock2 is still WIP) and replace it with Iris.

Done. I also added VST.

> If you are doing the editing in an editor with support for this, could you also split this very long line into multiple ones? Reviewing this very long line is hell on GitHub.

I have manually inserted new lines after each new item.

**Comment by Zimmi48** [comment]
Thanks!

**Comment by robbertkrebbers** [comment]
By the way, maybe we should also remove the link to https://github.com/coq/coq/wiki/List%20of%20Coq%20PL%20Projects This list is not very maintained and most projects there are pretty old.

If you agree with that, I can make an additional PR.

**Comment by Zimmi48** [comment]
I don't want to commit on this just yet because it would also mean removing the link to math projects and to teaching. And then what should we do with these three wiki pages?

**Comment by robbertkrebbers** [comment]
I see, these pages are very old too.

My 2 cents: do not list them on the Coq home page, and make clear on the wiki that they are just there for legacy's sake?

**Comment by Zimmi48** [comment]
Is it because you think it's going to be hard to keep such pages up-to-date, or because you think that they lack interest anyway?

**Comment by robbertkrebbers** [comment]
The former.

I think it would be great to have such pages, but we need someone to actively maintain them.

**Comment by Zimmi48** [comment]
OK, then I do agree with your recommendation.

**Pull request merged**
