### PR TITLE
Updating citing Coq in FAQ.

### PR DESCRIPTION
**Pull request by herbelin**
This is [BZ5766](https://coq.inria.fr/bugs/show_bug.cgi?id=5766) for its website part.

### CODE REVIEW

**Comment by ejgallego** [comment]
Merçi Hugo, I am wondering if also adding a more modern "@software" entry could make sense

```
@software{coq,
  author = {{The Coq Development Team}},
  title = {Coq},
  url = {https://coq.inria.fr},
  version = {8.7},
  date = {2017-10-15},
}
```

**Comment by herbelin** [comment]
> more modern "@software" entry could make sense

Yes, that would make sense also. One advantage of citing the reference manual is however a continuity in the recommended way of referring to Coq.

**Comment by ejgallego** [comment]
Continuity is certainly a very strong point.

**Comment by Zimmi48** [comment]
See also coq/coq#6180.

**Comment by letouzey** [comment]
Closing, since the FAQ in now hosted in the Wiki. Btw, the wiki page already mentions a version more recent than the above 😄.

**Pull request closed without merging**
